"""Add company and employee_id to user

Revision ID: 3715f3f8252d
Revises: d6ddd0d199f5
Create Date: 2026-03-02 11:47:10.389500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3715f3f8252d'
down_revision = 'd6ddd0d199f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('company')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
