"""add geolocation to trip

Revision ID: ede9c6e3a70b
Revises: e31d60157b08
Create Date: 2026-03-02 15:11:11.240028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede9c6e3a70b'
down_revision = 'e31d60157b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('end_lon')
        batch_op.drop_column('end_lat')
        batch_op.drop_column('start_lon')
        batch_op.drop_column('start_lat')

    # ### end Alembic commands ###
